/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardLicensesRouteImport } from './routes/dashboard/licenses'
import { Route as DashboardDownloadsRouteImport } from './routes/dashboard/downloads'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard/business'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminLicensesRouteImport } from './routes/admin/licenses'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/dashboard/support',
  path: '/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLicensesRoute = DashboardLicensesRouteImport.update({
  id: '/dashboard/licenses',
  path: '/dashboard/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDownloadsRoute = DashboardDownloadsRouteImport.update({
  id: '/dashboard/downloads',
  path: '/dashboard/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/dashboard/business',
  path: '/dashboard/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/admin/licenses',
  path: '/admin/licenses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/licenses': typeof DashboardLicensesRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/licenses'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/users'
    | '/dashboard/business'
    | '/dashboard/downloads'
    | '/dashboard/licenses'
    | '/dashboard/support'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/licenses'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/users'
    | '/dashboard/business'
    | '/dashboard/downloads'
    | '/dashboard/licenses'
    | '/dashboard/support'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/licenses'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/users'
    | '/dashboard/business'
    | '/dashboard/downloads'
    | '/dashboard/licenses'
    | '/dashboard/support'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardDownloadsRoute: typeof DashboardDownloadsRoute
  DashboardLicensesRoute: typeof DashboardLicensesRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/licenses': {
      id: '/dashboard/licenses'
      path: '/dashboard/licenses'
      fullPath: '/dashboard/licenses'
      preLoaderRoute: typeof DashboardLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/downloads': {
      id: '/dashboard/downloads'
      path: '/dashboard/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashboardDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/dashboard/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/admin/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardDownloadsRoute: DashboardDownloadsRoute,
  DashboardLicensesRoute: DashboardLicensesRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
