/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PinRouteImport } from './routes/pin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWarehousesRouteImport } from './routes/admin/warehouses'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminPurchasesRouteImport } from './routes/admin/purchases'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as ApiMeDashboardRouteImport } from './routes/api/me/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProductsCreateRouteImport } from './routes/admin/products.create'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products.$productId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehousesRoute = AdminWarehousesRouteImport.update({
  id: '/admin/warehouses',
  path: '/admin/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/admin/purchases',
  path: '/admin/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDashboardRoute = ApiMeDashboardRouteImport.update({
  id: '/api/me/dashboard',
  path: '/api/me/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsCreateRoute = AdminProductsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => AdminProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/platform': typeof PlatformRoute
  '/register': typeof RegisterRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/me/dashboard': typeof ApiMeDashboardRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/platform': typeof PlatformRoute
  '/register': typeof RegisterRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/me/dashboard': typeof ApiMeDashboardRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pin': typeof PinRoute
  '/platform': typeof PlatformRoute
  '/register': typeof RegisterRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/me/dashboard': typeof ApiMeDashboardRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pin'
    | '/platform'
    | '/register'
    | '/sales'
    | '/signup'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/employees'
    | '/admin/inventory'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/roles'
    | '/admin/warehouses'
    | '/admin/'
    | '/admin/products/create'
    | '/api/auth/$'
    | '/api/me/dashboard'
    | '/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pin'
    | '/platform'
    | '/register'
    | '/sales'
    | '/signup'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/employees'
    | '/admin/inventory'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/roles'
    | '/admin/warehouses'
    | '/admin'
    | '/admin/products/create'
    | '/api/auth/$'
    | '/api/me/dashboard'
    | '/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pin'
    | '/platform'
    | '/register'
    | '/sales'
    | '/signup'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/employees'
    | '/admin/inventory'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/roles'
    | '/admin/warehouses'
    | '/admin/'
    | '/admin/products/create'
    | '/api/auth/$'
    | '/api/me/dashboard'
    | '/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PinRoute: typeof PinRoute
  PlatformRoute: typeof PlatformRoute
  RegisterRoute: typeof RegisterRoute
  SalesRoute: typeof SalesRoute
  SignupRoute: typeof SignupRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminWarehousesRoute: typeof AdminWarehousesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMeDashboardRoute: typeof ApiMeDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouses': {
      id: '/admin/warehouses'
      path: '/admin/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AdminWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/admin/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/dashboard': {
      id: '/api/me/dashboard'
      path: '/api/me/dashboard'
      fullPath: '/api/me/dashboard'
      preLoaderRoute: typeof ApiMeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/create': {
      id: '/admin/products/create'
      path: '/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminProductsCreateRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsCreateRoute: typeof AdminProductsCreateRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsCreateRoute: AdminProductsCreateRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PinRoute: PinRoute,
  PlatformRoute: PlatformRoute,
  RegisterRoute: RegisterRoute,
  SalesRoute: SalesRoute,
  SignupRoute: SignupRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminWarehousesRoute: AdminWarehousesRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMeDashboardRoute: ApiMeDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
